### PR TITLE
Migrate noarch

### LINKED ISSUE #21: Preference for adding `aarch`/`ppc` vs. `noarch`
### Comment:

In the interest of fixing Linux ARM installs of Snakemake >7.x, I would like to add either the `aarch`/`ppc` platforms (started in #20), or switch to `noarch: python` (started in #22).

I believe both are possible, but I am relatively new to conda packaging, so I may be missing some details. From my understanding, if `noarch` works, it would be preferred as a single build can be used for all platforms. Are there any preferences from the package maintainers?

### PR DESCRIPTION
**Pull request by ReubenJ**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the  latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Might address [snakemake#1716](https://github.com/snakemake/snakemake/issues/1716).

Snakemake (>7.x) installs on linux arm platforms are currently blocked because this package is missing a valid 
version ARM targets. #20 adds `ppc` and `aarch` as a solution, but switching to `noarch` might be better as it 
removes the need for all for all of the platform-specific builds.

Closes #21.

### CODE REVIEW

**Comment by ReubenJ** [comment]
@fxwiegand @johanneskoester sorry for bumping, but would you be able to take a look at this? It is blocking Linux/ARM users from using Snakemake v7.x.

**Comment by fxwiegand** [comment]
@ReubenJ I'll try to ping Johannes in a second. This is definitely something he should have a look at instead of myself.

**Comment by ReubenJ** [comment]
@fxwiegand thanks! Much appreciated

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Thanks a lot, sorry for missing this. I don't see a reason to not use noarch here. In fact, I am unsure why it hasn't been noarch from the start.

**Comment by ReubenJ** [comment]
No problem! Thanks for getting it merged 🥳

**Pull request merged**
